name: Build Win
run-name: Build Win
on:
  workflow_dispatch: {}
jobs:
  main:
    runs-on: windows-2019
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          architecture: x64
      - run: flutter pub get
      - run: flutter build windows --release
